-- GENDER ENUM('M', 'F') NOT NULL,
-- -----------------------------------------------------
-- Schema CapivaraWars
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS CapivaraWars DEFAULT CHARACTER SET utf8 ;
USE CapivaraWars ;

-- -----------------------------------------------------
-- Table CapivaraWars.GAME_STATUS
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS CapivaraWars.GAME_STATUS (
  ID_GAME_STATUS INT NOT NULL AUTO_INCREMENT,
  NAME ENUM("CREATED", "ONGOING", "WIN", "LOSE", "DRAW") NOT NULL,
  PRIMARY KEY (ID_GAME_STATUS)
)ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table CapivaraWars.MATCH
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS CapivaraWars.MATCH (
  ID_MATCH INT NOT NULL AUTO_INCREMENT,
  START DATETIME NULL,
  END DATETIME NULL,
  ID_PRIZE_FOR_PLACE_1 INT NULL,
  ID_PRIZE_FOR_PLACE_2 INT NULL,
  ID_PRIZE_FOR_PLACE_3 INT NULL,
  ID_GAME_STATUS INT NOT NULL,
  PRIMARY KEY (ID_MATCH),
  CONSTRAINT fk_MATCH_CLOSURE_TYPE1
    FOREIGN KEY (ID_GAME_STATUS)
    REFERENCES CapivaraWars.GAME_STATUS (ID_GAME_STATUS)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table CapivaraWars.CHAMPIONSHIP
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS CapivaraWars.CHAMPIONSHIP (
  ID_CHAMPIONSHIP INT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(120) NOT NULL,
  START DATETIME NOT NULL,
  END DATETIME NULL,
  MAX_PLAYERS INT NOT NULL,
  MAX_MATCHES INT NOT NULL,
  CURRENT_NUMBER_OF_PLAYERS INT NULL,
  ID_PRIZE_FOR_PLACE_1 INT NOT NULL,
  ID_PRIZE_FOR_PLACE_2 INT NOT NULL,
  ID_PRIZE_FOR_PLACE_3 INT NOT NULL,
  ID_GAME_STATUS INT NOT NULL,
  PRIMARY KEY (ID_CHAMPIONSHIP),
  CONSTRAINT fk_CHAMPIONSHIP_GAME_STATUS1
    FOREIGN KEY (ID_GAME_STATUS)
    REFERENCES CapivaraWars.GAME_STATUS (ID_GAME_STATUS)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table CapivaraWars.PLAYER
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS CapivaraWars.PLAYER (
  ID_PLAYER INT NOT NULL AUTO_INCREMENT,
  NICK VARCHAR(45) NOT NULL,
  PASSWORD VARCHAR(45) NOT NULL,
  EMAIL VARCHAR(255) NOT NULL,
  ACCOUNT_BIRTHDAY DATETIME NOT NULL,
  AVATAR_URL VARCHAR(255) NOT NULL,
  FULL_NAME VARCHAR(100) NOT NULL,
  GENDER ENUM('M', 'F') NOT NULL,
  BIRTHDAY DATE NOT NULL,
  ONLINE BOOLEAN NULL,
  LAST_ACTIVATION_CODE VARCHAR(255) NULL,
  COINS INT NULL,
  SCORE INT NULL,
  WINS INT NULL,
  LOSSES INT NULL,
  DRAWS INT NULL,
  ACCURATE_SHOTS INT NULL,
  BAD_SHOTS INT NULL,
  SHOTS_RECEIVED INT NULL,
  MOVEMENTS INT NULL,
  MATCHES_PLAYED INT NULL,
  CHAMPIONSHIPS_PLAYED INT NULL,
  PRIZES_EARNED INT NULL,
  PRIMARY KEY (ID_PLAYER),
  UNIQUE INDEX NICK_UNIQUE (NICK ASC),
  UNIQUE INDEX EMAIL_UNIQUE (EMAIL ASC)
)ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table CapivaraWars.COLOR
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS CapivaraWars.COLOR (
  ID_COLOR INT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(120) NOT NULL,
  RGBA CHAR(9) NOT NULL,
  PRIMARY KEY (ID_COLOR)
)ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table CapivaraWars.CAPYBARA
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS CapivaraWars.CAPYBARA (
  ID_CAPYBARA INT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(45) NOT NULL,
  BIRTHDAY DATETIME NOT NULL,
  HP INT NULL,
  ID_COLOR INT NULL,
  ID_PLAYER INT NULL,
  PRIMARY KEY (ID_CAPYBARA),
  CONSTRAINT fk_CAPIVARA_COR
    FOREIGN KEY (ID_COLOR)
    REFERENCES CapivaraWars.COLOR (ID_COLOR)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table CapivaraWars.PRIZE
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS CapivaraWars.PRIZE (
  ID_PRIZE INT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(120) NOT NULL,
  COINS INT NOT NULL,
  ICON_URL VARCHAR(255) NOT NULL,
  CREATED_IN DATETIME NOT NULL,
  PRIMARY KEY (ID_PRIZE)
)ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table CapivaraWars.PRIZES_EARNED
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS CapivaraWars.PRIZES_EARNED (
  ID_PRIZES_EARNED INT NOT NULL AUTO_INCREMENT,
  ID_PLAYER INT NOT NULL,
  ID_PRIZE INT NOT NULL,
  PRIZE_DATETIME DATETIME NOT NULL,
  PRIMARY KEY (ID_PRIZES_EARNED),
  CONSTRAINT fk_JOGADOR_PREMIO_JOGADOR1
    FOREIGN KEY (ID_PLAYER)
    REFERENCES CapivaraWars.PLAYER (ID_PLAYER)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table CapivaraWars.CHAMPIONSHIPS_PLAYED
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS CapivaraWars.CHAMPIONSHIPS_PLAYED (
  ID_CHAMPIONSHIPS_PLAYED INT NOT NULL AUTO_INCREMENT,
  ID_CHAMPIONSHIP INT NOT NULL,
  ID_PLAYER INT NOT NULL,
  START DATETIME NULL,
  END DATETIME NULL,
  ID_GAME_STATUS INT NULL,
  PRIMARY KEY (ID_CHAMPIONSHIPS_PLAYED),
  CONSTRAINT fk_JOGADORES_EM_CAMPEONATO_JOGADOR1
    FOREIGN KEY (ID_PLAYER)
    REFERENCES CapivaraWars.PLAYER (ID_PLAYER)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table CapivaraWars.MATCHES_PLAYED
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS CapivaraWars.MATCHES_PLAYED (
  ID_MATCHES_PLAYED INT NOT NULL AUTO_INCREMENT,
  ID_PLAYER INT NOT NULL,
  ID_MATCH INT NOT NULL,
  ID_GAME_STATUS INT NULL,
  PRIMARY KEY (ID_MATCHES_PLAYED),
  CONSTRAINT fk_JOGADOR_PARTIDA_JOGADOR1
    FOREIGN KEY (ID_PLAYER)
    REFERENCES CapivaraWars.PLAYER (ID_PLAYER)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)ENGINE = InnoDB;

