-- -----------------------------------------------------
-- Schema CapivaraWars
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CapivaraWars` DEFAULT CHARACTER SET utf8 ;
USE `CapivaraWars` ;

-- -----------------------------------------------------
-- Table `CapivaraWars`.`GAME_STATUS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CapivaraWars`.`GAME_STATUS` (
  `ID_GAME_STATUS` INT NOT NULL AUTO_INCREMENT,
  `NAME` ENUM("CREATED", "ONGOING", "WIN", "LOSE", "DRAW") NOT NULL,
  PRIMARY KEY (`ID_GAME_STATUS`)
)ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CapivaraWars`.`MATCH`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CapivaraWars`.`MATCH` (
  `ID_MATCH` INT NOT NULL AUTO_INCREMENT,
  `START` DATETIME NULL,
  `END` DATETIME NULL,
  `ID_PRIZE_FOR_PLACED_1` INT NULL,
  `ID_PRIZE_FOR_PLACED_2` INT NULL,
  `ID_PRIZE_FOR_PLACED_3` INT NULL,
  `ID_GAME_STATUS` INT NULL,
  PRIMARY KEY (`ID_MATCH`),
  INDEX `FK_MATCH_ID_PRIZE_FOR_PLACED_1` (`ID_PRIZE_FOR_PLACED_1` ASC),
  INDEX `FK_MATCH_ID_PRIZE_FOR_PLACED_2` (`ID_PRIZE_FOR_PLACED_2` ASC),
  INDEX `FK_MATCH_ID_PRIZE_FOR_PLACED_3` (`ID_PRIZE_FOR_PLACED_3` ASC),
  CONSTRAINT `FK_MATCH_CLOSURE_TYPE1`
    FOREIGN KEY (`ID_GAME_STATUS`)
    REFERENCES `CapivaraWars`.`GAME_STATUS` (`ID_GAME_STATUS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CapivaraWars`.`CHAMPIONSHIP`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CapivaraWars`.`CHAMPIONSHIP` (
  `ID_CHAMPIONSHIP` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(120) NOT NULL,
  `START` DATETIME NOT NULL,
  `END` DATETIME NULL,
  `MAX_PLAYERS` INT NOT NULL,
  `MAX_MATCHES` INT NOT NULL,
  `CURRENT_NUMBER_OF_PLAYERS` INT NULL,
  `ID_PRIZE_FOR_PLACED_1` INT NULL,
  `ID_PRIZE_FOR_PLACED_2` INT NULL,
  `ID_PRIZE_FOR_PLACED_3` INT NULL,
  `ID_GAME_STATUS` INT NULL,
  PRIMARY KEY (`ID_CHAMPIONSHIP`),
  INDEX `FK_CHAMPIONSHIP_ID_PRIZE_FOR_PLACED_1` (`ID_PRIZE_FOR_PLACED_1` ASC),
  INDEX `FK_CHAMPIONSHIP_ID_PRIZE_FOR_PLACED_2` (`ID_PRIZE_FOR_PLACED_2` ASC),
  INDEX `FK_CHAMPIONSHIP_ID_PRIZE_FOR_PLACED_3` (`ID_PRIZE_FOR_PLACED_3` ASC),
  CONSTRAINT `FK_CHAMPIONSHIP_GAME_STATUS1`
    FOREIGN KEY (`ID_GAME_STATUS`)
    REFERENCES `CapivaraWars`.`GAME_STATUS` (`ID_GAME_STATUS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CapivaraWars`.`PLAYER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CapivaraWars`.`PLAYER` (
  `ID_PLAYER` INT NOT NULL AUTO_INCREMENT,
  `NICK` VARCHAR(45) NOT NULL,
  `PASSWORD` VARCHAR(45) NOT NULL,
  `EMAIL` VARCHAR(255) NOT NULL,
  `ACCOUNT_BIRTHDAY` DATETIME NOT NULL,
  `AVATAR_URL` VARCHAR(255) NOT NULL,
  `FULL_NAME` VARCHAR(100) NOT NULL,
  `GENDER` ENUM('M', 'F') NOT NULL,
  `BIRTHDAY` DATE NOT NULL,
  `ONLINE` TINYINT NULL,
  `LAST_ACTIVATION_CODE` VARCHAR(255) NULL,
  `COINS` INT NULL,
  `SCORE` INT NULL,
  `WINS` INT NULL,
  `LOSSES` INT NULL,
  `DRAWS` INT NULL,
  `ACCURATE_SHOTS` INT NULL,
  `BAD_SHOTS` INT NULL,
  `SHOTS_RECEIVED` INT NULL,
  `MOVEMENTS` INT NULL,
  `MATCHES_PLAYED` INT NULL,
  `CHAMPIONSHIPS_PLAYED` INT NULL,
  `PRIZES_EARNED` INT NULL,
  PRIMARY KEY (`ID_PLAYER`),
  UNIQUE INDEX `NICK_UNIQUE` (`NICK` ASC),
  UNIQUE INDEX `EMAIL_UNIQUE` (`EMAIL` ASC)
)ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CapivaraWars`.`COLOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CapivaraWars`.`COLOR` (
  `ID_COLOR` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(120) NOT NULL,
  `RGBA` CHAR(9) NOT NULL,
  PRIMARY KEY (`ID_COLOR`)
)ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CapivaraWars`.`CAPYBARA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CapivaraWars`.`CAPYBARA` (
  `ID_CAPYBARA` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(45) NOT NULL,
  `BIRTHDAY` DATETIME NOT NULL,
  `HP` INT NULL,
  `ID_COLOR` INT NULL,
  `ID_PLAYER` INT NULL,
  PRIMARY KEY (`ID_CAPYBARA`),
  INDEX `FK_CAPYBARA_ID_PLAYER` (`ID_PLAYER` ASC),
  CONSTRAINT `FK_CAPIVARA_COR`
    FOREIGN KEY (`ID_COLOR`)
    REFERENCES `CapivaraWars`.`COLOR` (`ID_COLOR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CapivaraWars`.`PRIZE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CapivaraWars`.`PRIZE` (
  `ID_PRIZE` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(120) NOT NULL,
  `COINS` INT NOT NULL,
  `ICON_URL` VARCHAR(255) NOT NULL,
  `CREATED_IN` DATETIME NOT NULL,
  PRIMARY KEY (`ID_PRIZE`)
)ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CapivaraWars`.`PRIZE_EARNED`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CapivaraWars`.`PRIZE_EARNED` (
  `ID_PRIZE_EARNED` INT NOT NULL AUTO_INCREMENT,
  `ID_PLAYER` INT NULL,
  `ID_PRIZE` INT NULL,
  `PRIZE_DATETIME` DATETIME NULL,
  PRIMARY KEY (`ID_PRIZE_EARNED`),
  INDEX `FK_PRIZE_EARNED_ID_PRIZE` (`ID_PRIZE` ASC),
  CONSTRAINT `FK_JOGADOR_PREMIO_JOGADOR1`
    FOREIGN KEY (`ID_PLAYER`)
    REFERENCES `CapivaraWars`.`PLAYER` (`ID_PLAYER`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CapivaraWars`.`CHAMPIONSHIP_PLAYED`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CapivaraWars`.`CHAMPIONSHIP_PLAYED` (
  `ID_CHAMPIONSHIP_PLAYED` INT NOT NULL AUTO_INCREMENT,
  `ID_CHAMPIONSHIP` INT NULL,
  `ID_PLAYER` INT NULL,
  `START` DATETIME NULL,
  `END` DATETIME NULL,
  `ID_GAME_STATUS` INT NULL,
  PRIMARY KEY (`ID_CHAMPIONSHIP_PLAYED`),
  INDEX `FK_CHAMPIONSHIP_PLAYED_ID_CHAMPIONSHIP` (`ID_CHAMPIONSHIP` ASC),
  INDEX `FK_CHAMPIONSHIP_PLAYED_ID_GAME_STATUS` (`ID_GAME_STATUS` ASC),
  CONSTRAINT `FK_JOGADORES_EM_CAMPEONATO_JOGADOR1`
    FOREIGN KEY (`ID_PLAYER`)
    REFERENCES `CapivaraWars`.`PLAYER` (`ID_PLAYER`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CapivaraWars`.`MATCH_PLAYED`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CapivaraWars`.`MATCH_PLAYED` (
  `ID_MATCH_PLAYED` INT NOT NULL AUTO_INCREMENT,
  `ID_PLAYER` INT NULL,
  `ID_MATCH` INT NULL,
  `ID_GAME_STATUS` INT NULL,
  PRIMARY KEY (`ID_MATCH_PLAYED`),
  INDEX `FK_MATCH_PLAYED_ID_MATCH` (`ID_MATCH` ASC),
  INDEX `FK_MATCH_PLAYED_ID_GAME_STATUS` (`ID_GAME_STATUS` ASC),
  CONSTRAINT `FK_JOGADOR_PARTIDA_JOGADOR1`
    FOREIGN KEY (`ID_PLAYER`)
    REFERENCES `CapivaraWars`.`PLAYER` (`ID_PLAYER`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)ENGINE = InnoDB;

