CREATE TABLE [JOGADOR](
    [ID_JOGADOR] INT NOT NULL PRIMARY KEY, -- Primary Key column
    [NICK] NVARCHAR(50) NOT NULL,
    [PASSWORD] NVARCHAR(50) NOT NULL,
    [DATA_NASCIMENTO] DATETIME NOT NULL,
    [URL_FOTO] NVARCHAR(255) NOT NULL,
    [NOME_COMPLETO] NVARCHAR(100) NOT NULL,
    [EMAIL] NVARCHAR(255) NOT NULL,
    [GENERO] nvarchar(10) NOT NULL CHECK (GENERO in ('M', 'F')),
    [STATUS] TINYINT NOT NULL,
    [DATAHORA_CRIACAO_CONTA] DATETIME NOT NULL,
    [ULTIMO_CODIGO_ATIVACAO] NVARCHAR(10) NULL,
    [VITORIAS] INT NOT NULL,
    [EMPATES] INT NOT NULL,
    [DERROTAS] INT NOT NULL,
    [MOEDAS]INT NOT NULL
); 

CREATE TABLE [PREMIO](
    [ID_PREMIO] INT NOT NULL PRIMARY KEY, -- Primary Key column
    [NOME] NVARCHAR(50) NOT NULL,
    [VALOR_MOEDAS] INT NOT NULL,
    [MOEDAS]INT NOT NULL
    -- Specify more columns here
);

CREATE TABLE CAMPEONATO (
  ID_CAMPEONATO INT IDENTITY NOT NULL PRIMARY KEY,
  [NOME] VARCHAR(120) NOT NULL,
  DATAHORA_INICIO DATETIME NOT NULL,
  DATAHORA_FIM DATETIME NULL,
  LIMITE_PARTICIPANTES INT NOT NULL,
  ID_PREMIO_PRIMEIRO_COLOCADO INT NOT NULL,
  ID_PREMIO_SEGUNDO_COLOCADO INT NOT NULL,
  ID_PREMIO_TERCEIRO_COLOCADO INT NOT NULL,
  ID_JOGADOR_VENCEDOR_PRIMEIRO INT NULL,
  ID_JOGADOR_VENCEDOR_SEGUNDO INT NULL,
  ID_JOGADOR_VENCEDOR_TERCEIRO INT NULL,
  CONSTRAINT [fk_CAMPEONATO_PREMIO1] FOREIGN KEY ([ID_PREMIO_PRIMEIRO_COLOCADO]) REFERENCES PREMIO ([ID_PREMIO]),
  CONSTRAINT [fk_CAMPEONATO_PREMIO2] FOREIGN KEY ([ID_PREMIO_SEGUNDO_COLOCADO]) REFERENCES PREMIO ([ID_PREMIO]),
  CONSTRAINT [fk_CAMPEONATO_PREMIO3] FOREIGN KEY ([ID_PREMIO_TERCEIRO_COLOCADO]) REFERENCES PREMIO ([ID_PREMIO]),
  CONSTRAINT [fk_CAMPEONATO_JOGADOR1] FOREIGN KEY ([ID_JOGADOR_VENCEDOR_PRIMEIRO]) REFERENCES JOGADOR ([ID_JOGADOR]),
  CONSTRAINT [fk_CAMPEONATO_JOGADOR2] FOREIGN KEY ([ID_JOGADOR_VENCEDOR_SEGUNDO]) REFERENCES JOGADOR ([ID_JOGADOR]),
  CONSTRAINT [fk_CAMPEONATO_JOGADOR3] FOREIGN KEY ([ID_JOGADOR_VENCEDOR_TERCEIRO]) REFERENCES JOGADOR ([ID_JOGADOR]),
);

CREATE TABLE [PARTIDA] (
  [ID_PARTIDA] INT NOT NULL PRIMARY KEY,
  [DATAHORA_INCIO] DATETIME NOT NULL,
  [DATAHORA_FIM] DATETIME NULL,
  [ID_JOGADOR_1] INT NOT NULL,
  [ID_JOGADOR_2] INT NOT NULL,
  [ID_JOGADOR_VENCEDOR] INT NULL,
  [EMPATOU] TINYINT NULL,
  [ID_CAMPEONATO] INT NULL,
  CONSTRAINT [fk_PARTIDA_JOGADOR1] FOREIGN KEY ([ID_JOGADOR_1]) REFERENCES JOGADOR ([ID_JOGADOR]),
  CONSTRAINT [fk_PARTIDA_JOGADOR2] FOREIGN KEY ([ID_JOGADOR_2]) REFERENCES JOGADOR ([ID_JOGADOR]),
  CONSTRAINT [fk_PARTIDA_CAMPEONATO] FOREIGN KEY ([ID_CAMPEONATO]) REFERENCES CAMPEONATO ([ID_CAMPEONATO])
);

CREATE TABLE COR (
  [ID_COR] INT NOT NULL IDENTITY,
  [NOME] VARCHAR(120) NOT NULL,
  PRIMARY KEY ([ID_COR]))
;

CREATE TABLE CAPIVARA (
  [ID_CAPIVARA] INT NOT NULL IDENTITY,
  [NOME] VARCHAR(45) NOT NULL,
  [DATAHORA_CRIACAO] DATETIME2(0) NOT NULL,
  [BARRA_VIDA] INT NOT NULL,
  [ID_COR] INT NOT NULL,
  [ID_JOGADOR] INT NOT NULL,
  PRIMARY KEY ([ID_CAPIVARA]),
  CONSTRAINT [fk_CAPIVARA_COR] FOREIGN KEY ([ID_COR]) REFERENCES COR ([ID_COR]) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT [fk_CAPIVARA_JOGADOR1] FOREIGN KEY ([ID_JOGADOR]) REFERENCES JOGADOR ([ID_JOGADOR]) ON DELETE NO ACTION ON UPDATE NO ACTION)
;

CREATE TABLE TIPO_ACESSORIO (
  [ID_TIPO_ACESSORIO] INT NOT NULL IDENTITY,
  [NOME] VARCHAR(120) NOT NULL,
  PRIMARY KEY ([ID_TIPO_ACESSORIO]))
;

CREATE TABLE ACESSORIO (
  [ID_ACESSORIO] INT NOT NULL IDENTITY,
  [NOME] VARCHAR(120) NOT NULL,
  [PRECO] INT NOT NULL,
  [URL_IMAGEM] VARCHAR(255) NOT NULL,
  [DATA_CRIACAO] DATETIME2(0) NOT NULL,
  [ID_TIPO_ACESSORIO] INT NOT NULL,
  PRIMARY KEY ([ID_ACESSORIO]), 
  CONSTRAINT [fk_ACESSORIO_TIPO_ACESSORIO] FOREIGN KEY ([ID_TIPO_ACESSORIO]) REFERENCES TIPO_ACESSORIO ([ID_TIPO_ACESSORIO])
    ON DELETE NO ACTION ON UPDATE NO ACTION)
;

CREATE TABLE ACESSORIOS_CAPIVARA (
  [ID_CAPIVARA] INT NOT NULL,
  [ID_ACESSORIO] INT NOT NULL,
  PRIMARY KEY ([ID_CAPIVARA], [ID_ACESSORIO]),
  CONSTRAINT [fk_CAPIVARA_ACESSORIO_CAPIVARA1] FOREIGN KEY ([ID_CAPIVARA]) REFERENCES CAPIVARA ([ID_CAPIVARA])
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT [fk_CAPIVARA_ACESSORIO_ACESSORIO] FOREIGN KEY ([ID_ACESSORIO]) REFERENCES ACESSORIO ([ID_ACESSORIO])
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);

CREATE TABLE PREMIOS_JOGADOR (
  [ID_JOGADOR] INT NOT NULL,
  [ID_PREMIO] INT NOT NULL,
  PRIMARY KEY ([ID_JOGADOR], [ID_PREMIO]),
  CONSTRAINT [fk_JOGADOR_PREMIO_JOGADOR1] FOREIGN KEY ([ID_JOGADOR]) REFERENCES JOGADOR ([ID_JOGADOR])
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT [fk_JOGADOR_PREMIO_PREMIO1] FOREIGN KEY ([ID_PREMIO]) REFERENCES PREMIO ([ID_PREMIO])
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);

CREATE TABLE JOGADORES_EM_CAMPEONATO (
  [ID_JOGADOR] INT NOT NULL,
  [ID_CAMPEONATO] INT NOT NULL,
  PRIMARY KEY ([ID_JOGADOR], [ID_CAMPEONATO]),
  CONSTRAINT [fk_JOGADOR_CAMPEONATO_JOGADOR1] FOREIGN KEY ([ID_JOGADOR]) REFERENCES JOGADOR ([ID_JOGADOR])
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT [fk_JOGADOR_CAMPEONATO_CAMPEONATO1] FOREIGN KEY ([ID_CAMPEONATO]) REFERENCES CAMPEONATO ([ID_CAMPEONATO])
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);
