-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema CapivaraWars
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema CapivaraWars
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CapivaraWars` DEFAULT CHARACTER SET utf8 ;
USE `CapivaraWars` ;

-- -----------------------------------------------------
-- Table `CapivaraWars`.`PREMIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CapivaraWars`.`PREMIO` (
  `ID_PREMIO` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(120) NOT NULL,
  `VALOR_EM_MOEDAS` INT NOT NULL,
  `URL_IMAGEM` VARCHAR(255) NOT NULL,
  `DATAHORA_CRIACAO` DATETIME NOT NULL,
  PRIMARY KEY (`ID_PREMIO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CapivaraWars`.`JOGADOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CapivaraWars`.`JOGADOR` (
  `ID_JOGADOR` INT NOT NULL AUTO_INCREMENT,
  `NICK` VARCHAR(45) NOT NULL,
  `SENHA` VARCHAR(45) NOT NULL,
  `DATAHORA_CRIACAO_CONTA` DATETIME NOT NULL,
  `URL_FOTO` VARCHAR(255) NOT NULL,
  `NOME_COMPLETO` VARCHAR(100) NOT NULL,
  `EMAIL` VARCHAR(255) NOT NULL,
  `GENERO` ENUM('M', 'F') NOT NULL,
  `DATA_NASCIMENTO` DATE NOT NULL,
  `ONLINE` TINYINT NULL,
  `ULTIMO_CODIGO_ATIVACAO` VARCHAR(255) NULL,
  `MOEDAS` INT NULL,
  `PONTUACAO` INT NULL,
  `VITORIAS` INT NULL,
  `EMPATES` INT NULL,
  `DERROTAS` INT NULL,
  `QTD_TIROS_CERTEIROS` INT NULL,
  `QTD_TIROS_RUINS` INT NULL,
  `QTD_TIROS_RECEBIDOS` INT NULL,
  `QTD_MOVIMENTOS` INT NULL,
  PRIMARY KEY (`ID_JOGADOR`),
  UNIQUE INDEX `NICK_UNIQUE` (`NICK` ASC),
  UNIQUE INDEX `EMAIL_UNIQUE` (`EMAIL` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CapivaraWars`.`CAMPEONATO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CapivaraWars`.`CAMPEONATO` (
  `ID_CAMPEONATO` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(120) NOT NULL,
  `DATAHORA_INICIO` DATETIME NOT NULL,
  `DATAHORA_FIM` DATETIME NULL,
  `LIMITE_PARTICIPANTES` INT NOT NULL,
  `QTD_ATUAL_PARTICIPANTES` INT NULL,
  `ID_PREMIO_PRIMEIRO_COLOCADO` INT NOT NULL,
  `ID_PREMIO_SEGUNDO_COLOCADO` INT NOT NULL,
  `ID_PREMIO_TERCEIRO_COLOCADO` INT NOT NULL,
  `ID_JOGADOR_VENCEDOR_PRIMEIRO` INT NULL,
  `ID_JOGADOR_VENCEDOR_SEGUNDO` INT NULL,
  `ID_JOGADOR_VENCEDOR_TERCEIRO` INT NULL,
  PRIMARY KEY (`ID_CAMPEONATO`),
  CONSTRAINT `fk_CAMPEONATO_PREMIO1`
    FOREIGN KEY (`ID_PREMIO_PRIMEIRO_COLOCADO`)
    REFERENCES `CapivaraWars`.`PREMIO` (`ID_PREMIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CAMPEONATO_PREMIO2`
    FOREIGN KEY (`ID_PREMIO_SEGUNDO_COLOCADO`)
    REFERENCES `CapivaraWars`.`PREMIO` (`ID_PREMIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CAMPEONATO_PREMIO3`
    FOREIGN KEY (`ID_PREMIO_TERCEIRO_COLOCADO`)
    REFERENCES `CapivaraWars`.`PREMIO` (`ID_PREMIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CAMPEONATO_JOGADOR1`
    FOREIGN KEY (`ID_JOGADOR_VENCEDOR_PRIMEIRO`)
    REFERENCES `CapivaraWars`.`JOGADOR` (`ID_JOGADOR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CAMPEONATO_JOGADOR2`
    FOREIGN KEY (`ID_JOGADOR_VENCEDOR_SEGUNDO`)
    REFERENCES `CapivaraWars`.`JOGADOR` (`ID_JOGADOR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CAMPEONATO_JOGADOR3`
    FOREIGN KEY (`ID_JOGADOR_VENCEDOR_TERCEIRO`)
    REFERENCES `CapivaraWars`.`JOGADOR` (`ID_JOGADOR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CapivaraWars`.`PARTIDA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CapivaraWars`.`PARTIDA` (
  `ID_PARTIDA` INT NOT NULL,
  `DATAHORA_INCIO` DATETIME NOT NULL,
  `DATAHORA_FIM` DATETIME NULL,
  `ID_JOGADOR_1` INT NOT NULL,
  `ID_JOGADOR_2` INT NOT NULL,
  `ID_JOGADOR_VENCEDOR` INT NULL,
  `EMPATOU` TINYINT NULL,
  `ID_CAMPEONATO` INT NULL,
  PRIMARY KEY (`ID_PARTIDA`),
  CONSTRAINT `fk_PARTIDA_CAMPEONATO1`
    FOREIGN KEY (`ID_CAMPEONATO`)
    REFERENCES `CapivaraWars`.`CAMPEONATO` (`ID_CAMPEONATO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PARTIDA_JOGADOR1`
    FOREIGN KEY (`ID_JOGADOR_VENCEDOR`)
    REFERENCES `CapivaraWars`.`JOGADOR` (`ID_JOGADOR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PARTIDA_JOGADOR2`
    FOREIGN KEY (`ID_JOGADOR_1`)
    REFERENCES `CapivaraWars`.`JOGADOR` (`ID_JOGADOR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PARTIDA_JOGADOR3`
    FOREIGN KEY (`ID_JOGADOR_2`)
    REFERENCES `CapivaraWars`.`JOGADOR` (`ID_JOGADOR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CapivaraWars`.`COR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CapivaraWars`.`COR` (
  `ID_COR` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(120) NOT NULL,
  `RGBA` CHAR(9) NOT NULL,
  PRIMARY KEY (`ID_COR`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CapivaraWars`.`CAPIVARA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CapivaraWars`.`CAPIVARA` (
  `ID_CAPIVARA` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(45) NOT NULL,
  `DATAHORA_CRIACAO` DATETIME NOT NULL,
  `BARRA_VIDA` INT NULL,
  `ID_COR` INT NULL,
  `ID_JOGADOR` INT NULL,
  PRIMARY KEY (`ID_CAPIVARA`),
  CONSTRAINT `fk_CAPIVARA_COR`
    FOREIGN KEY (`ID_COR`)
    REFERENCES `CapivaraWars`.`COR` (`ID_COR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CAPIVARA_JOGADOR1`
    FOREIGN KEY (`ID_JOGADOR`)
    REFERENCES `CapivaraWars`.`JOGADOR` (`ID_JOGADOR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CapivaraWars`.`TIPO_ACESSORIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CapivaraWars`.`TIPO_ACESSORIO` (
  `ID_TIPO_ACESSORIO` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(120) NOT NULL,
  PRIMARY KEY (`ID_TIPO_ACESSORIO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CapivaraWars`.`ACESSORIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CapivaraWars`.`ACESSORIO` (
  `ID_ACESSORIO` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(120) NOT NULL,
  `PRECO` INT NOT NULL,
  `URL_IMAGEM` VARCHAR(255) NOT NULL,
  `DATAHORA_CRIACAO` DATETIME NOT NULL,
  `ID_TIPO_ACESSORIO` INT NOT NULL,
  PRIMARY KEY (`ID_ACESSORIO`),
  CONSTRAINT `fk_ACESSORIO_TIPO_ACESSORIO1`
    FOREIGN KEY (`ID_TIPO_ACESSORIO`)
    REFERENCES `CapivaraWars`.`TIPO_ACESSORIO` (`ID_TIPO_ACESSORIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CapivaraWars`.`ACESSORIOS_DA_CAPIVARA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CapivaraWars`.`ACESSORIOS_DA_CAPIVARA` (
  `ID_CAPIVARA` INT NOT NULL,
  `ID_ACESSORIO` INT NOT NULL,
  `DATAHORA_AQUISICAO` DATETIME NOT NULL,
  `PRECO_PAGO` INT NOT NULL,
  PRIMARY KEY (`ID_CAPIVARA`, `ID_ACESSORIO`),
  CONSTRAINT `fk_CAPIVARA_ACESSORIO_CAPIVARA1`
    FOREIGN KEY (`ID_CAPIVARA`)
    REFERENCES `CapivaraWars`.`CAPIVARA` (`ID_CAPIVARA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CAPIVARA_ACESSORIO_ACESSORIO1`
    FOREIGN KEY (`ID_ACESSORIO`)
    REFERENCES `CapivaraWars`.`ACESSORIO` (`ID_ACESSORIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CapivaraWars`.`PREMIOS_DO_JOGADOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CapivaraWars`.`PREMIOS_DO_JOGADOR` (
  `ID_JOGADOR` INT NOT NULL,
  `ID_PREMIO` INT NOT NULL,
  `DATAHORA_AQUISICAO` DATETIME NOT NULL,
  PRIMARY KEY (`ID_JOGADOR`, `ID_PREMIO`),
  CONSTRAINT `fk_JOGADOR_PREMIO_JOGADOR1`
    FOREIGN KEY (`ID_JOGADOR`)
    REFERENCES `CapivaraWars`.`JOGADOR` (`ID_JOGADOR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_JOGADOR_PREMIO_PREMIO1`
    FOREIGN KEY (`ID_PREMIO`)
    REFERENCES `CapivaraWars`.`PREMIO` (`ID_PREMIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CapivaraWars`.`JOGADORES_EM_CAMPEONATO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CapivaraWars`.`JOGADORES_EM_CAMPEONATO` (
  `ID_JOGADOR` INT NOT NULL,
  `ID_CAMPEONATO` INT NOT NULL,
  `DATAHORA_INICIO_PARTICIPACAO` DATETIME NOT NULL,
  `DATAHORA_FIM_PARTICIPACAO` DATETIME NULL,
  PRIMARY KEY (`ID_JOGADOR`, `ID_CAMPEONATO`),
  CONSTRAINT `fk_JOGADOR_CAMPEONATO_JOGADOR1`
    FOREIGN KEY (`ID_JOGADOR`)
    REFERENCES `CapivaraWars`.`JOGADOR` (`ID_JOGADOR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_JOGADOR_CAMPEONATO_CAMPEONATO1`
    FOREIGN KEY (`ID_CAMPEONATO`)
    REFERENCES `CapivaraWars`.`CAMPEONATO` (`ID_CAMPEONATO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
